name: Multiples jops
on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'master'
jobs:
  job1: 
     name: Job1 Starting with a Maven workflow template
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - name: set up node
        uses: actions/setup-node@v1
      - name: Install bats
        run: npm install -g bats
      - name: execute a cmd
        run: bats -v
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml


  job2:
    name: job2 Specifying the JVM and node version and architecture
    needs: job1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install node.js packages
        run: npm install

  job3_publish:
    name: publish snapshot to jfrog
    needs: job1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Upload artifact to jfrog
        run: |
              echo "-------------------PREVIOUS SETTINGS.xml------------------------------"
              cat ~/.m2/settings.xml

              java -version
              cp config/settings.xml ~/.m2/settings.xml
              mvn -ntp package deploy -Pprod -DskipTests


  job5_release:
    name: publish release to jfrog
    needs: job3_publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Upload artifact to jfrog
        continue-on-error: true
        env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              cp config/settings.xml ~/.m2/settings.xml
              mvn -ntp release:prepare release:perform -DskipTests